export const FETCH_DATA = 'HOME/FETCH_DATA';
export const REQUESTED_DATA = 'HOME/REQUESTED_DATA';

export const FETCH_POST_DATA = 'HOME/FETCH_POST_DATA';
export const REQUESTED_POST_DATA = 'HOME/REQUESTED_POST_DATA';

export const SHOW_MESSAGE = 'APP/SHOW_MESSAGE';
export const MAKE_MESSAGE_VISIBLE = 'APP/MAKE_MESSAGE_VISIBLE';
export const HIDE_MESSAGE = 'APP/HIDE_MESSAGE';

export const CHANGE_INPUT_VALUE = 'APP/CHANGE_INPUT_VALUE';

export const REQUESTED_BOARD = 'BOARD/REQUESTED_DATA';
export const FETCH_BOARD = 'BOARD/FETCH_DATA';
export const FETCH_POST_BOARD = 'BOARD/FETCH_POST_DATA';

export const DELETE_DATA = 'BOARD/DELETE_DATA';
export const DELETE_BOARD = 'HOME/DELETE_BOARD';

export const SHOW_MODAL = 'APP/SHOW_MODAL';
export const HIDE_MODAL = 'APP/HIDE_MODAL';
